ProjectBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import authenticate

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('post.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.PostHome, name='home'),
    path("deatils/<str:slug>", views.Details, name="details"),
    path("new_post", views.CreatePost, name='new_post'),
    path('login/', views.UserLogin, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path("register/", views.UserRegister, name="register"),
    path("profile-update/", views.UpdateProfile, name='profile-update'),
    path("search/", views.Query, name='search'),
    path("profile<str:pk>/", views.UserProfile, name='profile'),
    path("like/", views.Like, name='like_post'),

]

post/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from embed_video.fields import EmbedVideoField


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profile_images/',
                                      default='profile_images/default.png')
    username = models.CharField(max_length=100),
    email = models.EmailField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True),

    def __str__(self):
        return str(self.user.username)


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=2000, null=True, blank=True, unique=True)
    body = models.TextField()
    posted = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_created=True, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    like_count = models.BigIntegerField(default='0')
    image = models.ImageField(upload_to='static/images/%Y/%m', null=True, blank=True)
    video = EmbedVideoField(null=True, blank=True)
    url = EmbedVideoField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    post_views = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.title

    @property
    def num_likes(self):
        return self.likes.all().count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + "-" + str(self.posted))
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-posted']


LIKE_CHOICES = (
    ('lIKE', 'lIKE'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body

templates/details.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <style>
        section {
            padding: 80px;
        }

        .details-card {
            background: #ecf0f1;
        }

        .card-content {
            background: #ffffff;
            border: 4px;
            box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
        }

        .card-img {
            position: relative;
            overflow: hidden;
            border-radius: 0;
            z-index: 1;
        }

        .card-img img {
            width: 100%;
            height: auto;
            display: block;
        }

        .card-img span {
            position: absolute;
            top: 15%;
            left: 12%;
            background: #1ABC9C;
            padding: 16px;
            color: #fff;
            font-size: 12px;
            border-radius: 4px;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            -ms-border-radius: 4px;
            -o-border-radius: 4px;
            transform: translate(-50%, -50%);
        }

        .card-img span h4 {
            font-size: 12px;
            margin: 0;
            padding: 10px 5px;
            line-height: 0;
        }

        .card-desc {
            padding: 1.25rem;
        }

        .card-desc h3 {
            color: #000000;
            font-weight: 600;
            font-size: 1.5em;
            line-height: 1.3em;
            margin-top: 0;
            margin-bottom: 15px;
            padding: 0;
        }

        .card-desc p {
            color: #747373;
            font-weight: 400;
            font-size: 1em;
            line-height: 1.5;
            margin: 0 0 20px;
            padding: 0;
            font-family: 'Raleway', sans-serif;
        }


        .row h5 {

            color: #5b80b2;
        }

        .row strong {

            color: #5b80b2;
        }
         span{
           padding: 10px;
            color: #5b80b2;
        }

    </style>

    <section class="details-card">
        <div class="container-center">
            <div class="row">
                <div class="col-md-9">
                    <div class="card-content">
                        <div class="card-img">
                            <img src="{{ post.image.url }}" alt="">
                        </div>
                        <span class="card-desc">
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.body }}</p>

                            <img src="{{ post.author.profile.profile_image.url }}"
                                 class="img-circle"

                                 height="45" width="45" alt="Avatar"> <a href="{% url 'profile' pk=post.author_id %}">
                            <strong>{{ post.author.profile }}</strong></a>
                            <hr>
                            <p>
                                <italic>{{ post.posted }}</italic>
                                <italic> | Category : <strong>{{ post.category }}</strong></italic>
                            </p>

                            <form action="" method="POST" class="ui form">
                                {% csrf_token %}
                                <input type="hidden" name="'post_id" value="{{ post.id }}">
                                {% if user not in post.likes.all %}
                                    <button class="btn btn-success" name="post_id" value="{{ post.id }}" type="submit">
                                        Like
                                    </button>
                                {% else %}
                                    <button class="btn btn-danger" name="post_id" value="{{ post.id }}" type="submit">
                                        Unlike
                                    </button>
                                {% endif %}
                           <button type="button" class="btn btn-primary" id="liveToastBtn">{{ post.num_likes }} Likes</button>

                        <div class="toast-container position-relative bottom-0 end-0 p-65">
                          <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                            <div class="toast-header">
                              <strong class="me-auto">Last Likes</strong>
                              <small>Last liked by @{{ post.likes.first }}</small>
                              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                            </div>
                               {% for like in post.likes.all %}
                            <div class="toast-body">
                              <img src="{{ like.profile.profile_image.url }}"
                                 class="img-circle"

                                 height="25" width="25" alt="">
                             <span>{{ like.username }},</span>
                            </div>
                              {% endfor %}
                          </div>
                        </div>


{#                            <span> {{ post.num_likes }} Likes</span>#}
{#                            (#}
{#                            {% for like in post.likes.all %}#}
{#                            <span> {{ like.username }},</span>#}
{#                            {% endfor %}#}
{#                                            )#}

                                <br>
                                <span class="position-relative">
                                    Comments <i
                                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning">{{ post.comments.count }} </i></span>
                            </form>
                                </span>
                        </div>
                    </div>
                </div>
                <h4>Leave a Comment:</h4>
                <form method="post" action="">
                    {% csrf_token %}
                    {#                                        {{ forms.as_div }}#}
                    <div class="form-group">
                        <label>
                    <textarea name="body" class="form-control" rows="3" required
                              placeholder="Comment Here......."></textarea>
                        </label>
                    </div>
                    <button type="submit" class="btn btn-success">Add Post</button>
                </form>
                <br><br>

                <p><span class="badge"></span> Comments:</p><br>
                <div class="row">
                    {% for comment in post.comments.all %}
                        <article>
                            <img src="{{ comment.user.profile.profile_image.url }}"
                                 class="img-circle"

                                 height="25" width="25" alt="Avatar">

                            <strong>{{ comment.user }}</strong>

                            <italic class="text-muted">Created at {{ comment.posted|timesince }} ago</italic>
                            <hr>
                            <h4>{{ comment.body }}</h4>
                        </article>
                        <hr>
                    {% endfor %}
                </div>
            </div>
    </section>
    <script>
    const toastTrigger = document.getElementById('liveToastBtn')
const toastLiveExample = document.getElementById('liveToast')
if (toastTrigger) {
  toastTrigger.addEventListener('click', () => {
    const toast = new bootstrap.Toast(toastLiveExample)

    toast.show()
  })
}
    </script>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Roboto+Condensed:400,400i,700,700i');

        section {
            padding: 60px 20px;

        }

        .details-card {
            background: whitesmoke;
        }

        .card-content {
            background: snow;
            border: 2px;
            box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
            padding: 20px 10px 20px 12px;
            position: relative;

        }

        .card-img {
            position: relative;
            overflow: hidden;
            border-radius: 0;
            z-index: 1;

        }

        .card-img img {
            width: 100%;
            height: 200px;
            display: block;
        }

        .card-img span {
            position: absolute;
            top: 15%;
            left: 12%;
            background: #1ABC9C;
            padding: 6px;
            color: #fff;
            font-size: 12px;
            border-radius: 4px;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            -ms-border-radius: 4px;
            -o-border-radius: 4px;
            transform: translate(-50%, -50%);
        }

        .card-img span h4 {
            font-size: 12px;
            margin: 0;
            padding: 10px 5px;
            line-height: 0;
        }

        .card-desc {
            padding: 1.25rem;
        }

        .card-desc h3 {
            color: #000000;
            font-weight: 600;
            font-size: 1.5em;
            line-height: 1.3em;
            margin-top: 0;
            margin-bottom: 5px;
            padding: 0;
        }

        .card-desc p {
            color: #747373;
            font-size: 14px;
            font-weight: 400;
            line-height: 1.5;
            margin: 0 0 20px;
            padding: 0;
            font-family: 'Raleway', sans-serif;
        }

        .btn-card {
            background-color: #1ABC9C;
            color: #fff;
            box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
            padding: .84rem 2.14rem;
            font-size: .81rem;
            -webkit-transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, -webkit-box-shadow .15s ease-in-out;
            -o-transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out;
            transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out, -webkit-box-shadow .15s ease-in-out;
            margin: 0;
            border: 0;
            -webkit-border-radius: .125rem;
            border-radius: .125rem;
            cursor: pointer;
            text-transform: uppercase;
            white-space: normal;
            word-wrap: break-word;
        }

        .btn-card:hover {
            background: orange;
        }

        a.btn-card {
            text-decoration: none;
            color: #fff;
        }
        span{
           padding: 10px;
            color: #5b80b2;
        }
    </style>

    <section class="details-card">
        <div class="container-flow">
            <div class="row">
                {% for post in posts %}
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xlg-6">
                        <div class="card-content">
                            <div class="card-img ">
                                <img src="{{ post.image.url }}" alt="">
                                <span><h4>{{ post.category }}</h4></span>
                            </div>
                            <div class="card-desc">
                                <h3>{{ post.title }}</h3>
                                <p>{{ post.body|truncatechars:90 }}</p>
                                <a href="{% url 'details' post.slug %}" class="btn-card">Read More</a>
                                <hr>
                                <img src="{{ post.author.profile.profile_image.url }}"
                                     class="img-circle"

                                     height="45" width="45" alt="Avatar"> <a
                                    href="{% url 'profile' pk=post.author_id %}">
                                <i>{{ post.author }}</i></a>
                                <hr>
                                <p>
                                    <italic>Posted at :{{ post.posted }}</italic>
                                </p>
                               <span  class=" position-relative">
                                    Likes <span
                                        class="position-absolute translate-middle badge rounded-pill bg-danger">{{ post.num_likes }} </span></span>

                                <span class="position-relative">
                                    Comments <i
                                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning">{{ post.comments.count }} </i></span>
                                                            `
                                <span class="position-relative">
                                    Views <i
                                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-info">{{ post.post_views }} </i></span>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

                <br/><br/>
       <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
        {% if posts.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page=1">First &laquo </a></li>
        <li class="page-item ">
            <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
    {% endif %}

{#  {% for i in nums %}#}
{#      <li class="page-item"><a href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>#}
{##}
{#  {% endfor %}#}

    <li class="page-item disabled"><a href="#" class="page-link">Page {{ posts.number }} of
        {{ posts.paginator.num_pages }}</a></li>

    {%  if posts.has_next %}
      <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.paginator.num_pages }}">Last &raquo </a></li>
            {% endif %}
      </ul>
    </nav>

}
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    <script src="{% static '/js/main.js' %}"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}



<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
{% load static %}
<style>
    a {
        text-decoration: none;
        color: #0c7f90;
        font-size: 25px;
        margin-top: 10px;
        margin-right: 50px;
        margin-left: auto;
        font-weight: 500;
        cursor: pointer;
    }

    i {
        text-decoration: none;
        color: #0c7f90;
        font-size: 25px;
        margin-top: 10px;
        margin-right: 50px;
        margin-left: auto;
        font-weight: 500;
        cursor: pointer;
    }
</style>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
    <!-- Button trigger modal -->
<a type="button"  data-bs-toggle="modal" data-bs-target="#exampleModal">
 bookPost
</a>

<!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Welcome in Our blogs!! Here you can read our rules and regulations</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-info">

                Why do we use it?

                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

              </div>
            </div>
          </div>
        </div>

{#        <i class="text info" href="{% url 'home' %}">bookPost</i>#}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'new_post' %}">Add New Post</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'home' %}" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Category
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <a href="{% url 'home' %}?category={{ category.name }}" class="nav-link px-0"> <span
                                    class="d-none d-sm-inline">{{ category.name }}</span>
                                <br>({{ category.post_set.count }})
                            </a>
                        {% endfor %}
                    </ul>
                </li>
            </ul>

            {% if user.is_authenticated %}
                <div class="dropdown md-4">
                    <a href="#"
                       class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile.profile_image.url }}" alt="" width="40" height="40"
                             class="rounded-circle">
                        <i class=""> @{{ user.username }}</i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-light text-small shadow">
                        <li><a class="dropdown-item" href="{% url 'profile-update' %}">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'profile' pk=user.id %}">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
                    </ul>
                </div>

            {% else %}
                <span><a type="submit" href="{% url 'login' %}" class="btn  btn-info text-light">Login</a>
                <a type="submit" href="{% url 'register' %}" class="btn  btn-info text-light">Register</a></span>
            {% endif %}
            <form class="d-flex" role="search" method="get" action="{% url 'search' %}">
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-info" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/new_post.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins');

/* BASIC */

{#html {#}
{#  background-color: cadetblue;#}


body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}



h2 {
  text-align: center;
  font-size: 26px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px;
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}




/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: cornflowerblue;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
    color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}




/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
}

#icon {
  width:20%;
}

* {
  box-sizing: border-box;
}
    </style>
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active">Add Post </h2>

   <form action="{% url 'new_post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
         {{ form.as_p }}
      <input type="submit" class="fadeIn fourth" value="Add Post">
    </form>



  </div>
</div>
{% endblock %}